### ISSUE TITLE
Print source translation infos

### ISSUE THREAD

**Issue by offline-first** [Tienisto/flutter-fast-i18n#55]
Hello @Tienisto 

For the translators it would be helpful to have some information like source keys count and word count.
Can you output this information to the console after the build process?

Thank you for the best localization plugin ✨

**Comment by Tienisto** [comment]
Thanks for the compliment! I appreciate that :)

What do you mean by "source keys"? Is it the same as the `strings` count in the generated file?

Counting words seems to be an unecessary step because every translation needs to be parsed. Maybe a custom command like `flutter pub run fast_i18n analyse` would be more suitable.

**Comment by offline-first** [comment]
I mean with "source keys" the count of all json keys like this:
```json
{
  "key_0": "word1 word2",
  "key_1": {
    "key_2": "word3"  
  }
}
```
source keys = 3
words = 3 
chars = 15

A custom command it is also good!

**Comment by Tienisto** [comment]
There is now a new command in `5.11.0`:

```sh
flutter pub run fast_i18n stats
```

Just leave some comments or create a new issue if you need some improvements :)

**Comment by offline-first** [comment]
Perfect, thank you so much!
